In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
##sentences
sent = ['I love my dog',
             'I love my cat',
                'You love my dog!',
                'Do you think my dog is amazing?']


In [4]:
sent

['I love my dog',
 'I love my cat',
 'You love my dog!',
 'Do you think my dog is amazing?']

In [5]:
##deinfing vocabulary size
voc_size=10000

In [7]:
#one hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent]
onehot_repr


[[9374, 4392, 2229, 53],
 [9374, 4392, 2229, 2781],
 [8256, 4392, 2229, 53],
 [5721, 8256, 272, 2229, 53, 3717, 6455]]

In [8]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [9]:
sent_len=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 9374, 4392, 2229,   53],
       [   0,    0,    0,    0, 9374, 4392, 2229, 2781],
       [   0,    0,    0,    0, 8256, 4392, 2229,   53],
       [   0, 5721, 8256,  272, 2229,   53, 3717, 6455]])

In [10]:
##feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9374, 4392, 2229,   53])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 54ms/step


array([[ 0.02748552, -0.01482042, -0.00797793,  0.03808227,  0.02882839,
        -0.01105198,  0.03051462, -0.04973437, -0.02015027,  0.00940255],
       [ 0.02748552, -0.01482042, -0.00797793,  0.03808227,  0.02882839,
        -0.01105198,  0.03051462, -0.04973437, -0.02015027,  0.00940255],
       [ 0.02748552, -0.01482042, -0.00797793,  0.03808227,  0.02882839,
        -0.01105198,  0.03051462, -0.04973437, -0.02015027,  0.00940255],
       [ 0.02748552, -0.01482042, -0.00797793,  0.03808227,  0.02882839,
        -0.01105198,  0.03051462, -0.04973437, -0.02015027,  0.00940255],
       [-0.02977194, -0.02344383, -0.04285941,  0.04292755, -0.04809415,
        -0.04236621,  0.00413127,  0.00553644, -0.04243963,  0.00666505],
       [-0.04620171, -0.00301734, -0.02228199, -0.00635887, -0.01902832,
        -0.02109348,  0.00452119,  0.03961166, -0.00208284, -0.01448982],
       [ 0.02710119,  0.04434279,  0.00508686, -0.01691134,  0.03952234,
        -0.00982927, -0.02495962, -0.03114988